### ISSUE TITLE
function components

### ISSUE THREAD

**Issue by talp101** [SagiMedina/Aviya#1]
it will be a great feature if you apply components as stateless function just like React.

by the way, awesome lib, truly love it!

**Comment by SagiMedina** [comment]
Thanks!
Aviya's components are stateless, I guess you meant you would like to write component as function like React's stateless function. That is a great idea! I will implement it in the next version.

**Comment by talp101** [comment]
Exactly what I meant.
בתאריך 8 ביול' 2016 6:42 PM,‏ "SagiMedina" notifications@github.com כתב:

**Comment by SagiMedina** [comment]
Done
