### ISSUE TITLE
How to update a component

### ISSUE THREAD

**Issue by rbiggs** [SagiMedina/Aviya#2]
Nice library for rendering components. However, is there a way to re-render a component with new data? For example, say you had a list, and you have a form where the user can add new items, how would you update the list?

**Comment by SagiMedina** [comment]
The same as you would do without any library or framework.
The idea behind  Avia is to keep it as Vanilla as you can but still use stuff like declarative views and encapsulated components.

I am working on updating this library so any comment will be appreciated.
